apps/blog/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',

    # Examples:
    # url(r'^$', 'shop.views.home', name='home'),
)

myblog/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', 'apps.blog.views.index', name='index'),
    url(r'^add_blog/', 'apps.blog.views.add_blog', name='add_blog'),
    url(r'^blog/', include('apps.blog.urls', namespace='blog')),
    url(r'^(?P<id>\d+)/', 'apps.blog.views.type_blog', name='type_blog'),
    url(r'^type/(?P<id>\d+)/', 'apps.blog.views.type_id', name='type_id'),
    url(r'^profile/', 'apps.blog.views.profile', name='profile'),
    url(r'^logout/$', 'apps.blog.views.user_logout', name='logout'),
    url(r'^login/$', 'apps.blog.views.login', name='login'),
    url(r'^delete/(?P<id>\d+)/$', 'apps.blog.views.delete', name='delete'),
    url(r'^register/', 'apps.blog.views.register', name='register'),
    # Examples:
    # url(r'^$', 'testdrive.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

apps/blog/models.py
from datetime import datetime
from django.contrib.auth.models import User
from django.db import models


class BlogType(models.Model):
    type_name = models.CharField(max_length=200)

    def __unicode__(self):
        return self.type_name

class Blog(models.Model):
    blog_type = models.ForeignKey(BlogType)
    blog_name = models.CharField(max_length=200)
    add_date = models.DateTimeField(default=datetime.now())
    user = models.ForeignKey(User)
    blog_text = models.TextField()

    def __unicode__(self):
        return self.blog_name

class Comments(models.Model):
    user = models.ForeignKey(User)
    blog = models.ForeignKey(Blog)
    add_date = models.DateTimeField(default=datetime.now())
    comment = models.TextField()
    def __unicode__(self):
        return self.comment

apps/blog/forms.py
from django import forms
from django.contrib.auth.models import User
from models import Blog, Comments

class Add(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('blog_type', 'blog_name', 'add_date', 'blog_text')


class Comment(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('add_date', 'comment',)


class Register(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())
	class Meta:
		model = User
		fields = ('first_name', 'last_name', 'email', 'username', 'password')

apps/blog/views.py
from django.core.context_processors import csrf
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from forms import Add, Comment, Register
from models import Blog, BlogType, Comments
from django.contrib.auth import login as auth_login, authenticate, logout



def register(request):
    blogtype = BlogType.objects.all()
    if request.method == 'POST':
        form = Register(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(request.POST['password'])
            user.save()
            new_user = authenticate(username=request.POST['username'], password=request.POST['password'])
            auth_login(request, new_user)
            return redirect('/')
    else:
        form = Register()
    return render(request, "register.html", {'form':form, 'blogtype': blogtype})


def add_blog(request):
    blogtype = BlogType.objects.all()
    if request.method == 'POST':
        form = Add(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            return redirect('/')
    else:
        form = Add()
    return render(request, 'add_blog.html', {'form': form, 'blogtype': blogtype})

def index(request):
    blogtype = BlogType.objects.all()
    return render(request, 'index.html', {'blogtype': blogtype})

def base(request):
    blogtyp = BlogType.objects.all()
    return render(request, 'base.html', {'blogtyp': blogtyp})

def type_blog(request, id):
    blogtype = BlogType.objects.all()
    blogtypes = BlogType.objects.all().get(pk=id)
    return render(request, 'types.html', {'blogtypes': blogtypes, 'blogtype': blogtype})


def type_id(request, id):
    blogtype = BlogType.objects.all()
    blog = Blog.objects.all().get(pk=id)
    comment = Comments.objects.all()
    if request.method == 'POST':
        form = Comment(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.blog = blog
            instance.user = request.user
            instance.save()

    else:
        form = Comment()
    c = dict(comment=comment, blog=blog, blogtype=blogtype, form=form)
    c.update(csrf(request))
    return render(request, 'type_id.html', c)

def login(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            auth_login(request, user)
            return HttpResponseRedirect('/')
        else:
            return HttpResponse('<h3> you need login again </h3>')
    else:
        blogtype = BlogType.objects.all()
        return render(request, 'login.html', {'blogtype': blogtype})

def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')

def profile(request):
    blog = Blog.objects.filter(user=request.user)
    blogtype = BlogType.objects.all()
    return render(request, 'profile.html', {'blogtype': blogtype, 'blog': blog})

def delete(request, id):
    blogtype = BlogType.objects.all()
    authenticated_user_blog = Blog.objects.filter(user=request.user).get(pk=id).delete()
    return render(request, "delete.html", {'blog': authenticated_user_blog, 'blogtype': blogtype})

apps/blog/templates/add_blog.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block content %}
    <div class="add-blog">
        <form method="post" action="">
                {% csrf_token %}
                {{ form|bootstrap }}
                    <input class="btn btn-index btn-lg active" type="submit" value="Опубликовать" />
        </form>
    </div>
{% endblock %}

apps/blog/templates/base.html
{% load staticfiles %}
<html>
<head lang="en">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
    <title> News </title>
</head>
<body>
<h1 class="h1-index">News-Blog</h1>
<nav class="navbar navbar-inverse">
          <div class="container-fluid">
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-9">
              <ul class="nav navbar-nav">
                <li><a href="/">Домой</a></li>
                  {% for blogtype in blogtype %}
                  <li><a href="{% url 'type_blog' blogtype.id %}">{{ blogtype.type_name }}</a></li>
                  {% endfor %}

                      {% if user.is_active and user.is_staff %}
                        <li><a href="/add_blog">Добавить</a></li>
                         <li><a href="/profile">Личный кабинет</a></li>
                        <li><a class="job-logout" href="/logout">Выход</a></li>
                    {% elif user.is_authenticated %}
                         <li><a class="job-logout" href="/logout">Выход</a></li>
                      {% else %}
                         <li><a href="/login">Вход</a></li>
                      {% endif %}
              </ul>
            </div>
          </div>
    </nav>
{% block content %}

{% endblock %}
</body>
</html>

apps/blog/templates/delete.html
{% extends "base.html" %}


{% block content %}
        <div class="delete"> <h4>Имя: {{ user.first_name }}</h4><br/>
        <h4>Фамилия: {{ user.last_name }}</h4><br/>
        <h4>Почтовый адрес: {{ user.email }}</h4><br/>

           <h3> вы удалили эту статю!!!</h3> </div>
{% endblock %}

apps/blog/templates/index.html
{% extends 'base.html' %}

{% block content %}
<body>
<div class="block-body">
    {% if user.is_authenticated %}
        <h3>Добропожаловать {{ user.username }} на мой Блог!!!</h3>
    {% else %}
    <h3> Добропожаловать в мой блог тут вы узнаете про последние новости и самые новые технологи нашего времени.
    </h3>
    {% endif %}
</div>
</body>
{% endblock %}

apps/blog/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="delete">
<h3>Вход только для определеной количество людей</h3>
<form class="blog-login" method="post" action="">
	    {% csrf_token %}

	    Имя пользователя: <input type="text" class="form-control" name="username" value="" size="50" />
	            <br />
	    Пароль: <input type="password" class="form-control" name="password" value="" size="50" />
	            <br />
            <input class="btn btn-primary" type="submit" value="Вход" />
            <a class="btn btn-primary" href="/register/"> Регистрация</a>
</form>
    </div>

    {% endblock %}

apps/blog/templates/profile.html
{% extends 'base.html' %}

{% block content %}
<body>
<div class="block-body">
    <h4>Имя: {{ user.first_name }}</h4><br/>
	<h4>Фамилия: {{ user.last_name }}</h4><br/>
	<h4>Почтовый адрес: {{ user.email }}</h4><br/><hr/>

    {% for blog in blog %}
        <h3><a href="/type/{{ blog.id }}/ ">{{ blog.blog_name }}</a> </h3><hr/>
        <a href='/delete/{{ blog.id }}/'> Delete</a> <br/><hr/>
    {% endfor %}
</div>
</body>
{% endblock %}

apps/blog/templates/register.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block content %}
	<div class="register-body">
			<form class="register" method="post" action="/register/">
			{% csrf_token %}

   <h5> {{ form|bootstrap }}</h5><br/>
			<input type="submit" value="Регистрация" class="btn btn-register btn-lg active"/>
		</form>
	</div>
</div>
{% endblock %}

apps/blog/templates/type_id.html
{% extends 'base.html' %}

{% block content %}
<body>
<div class="block-body">
    <h1>{{ blog.blog_name }}</br></h1>
   Тип: {{ blog.blog_type }}</br>
   Добавил: {{ blog.user }}</br>
   Время добовление: {{ blog.add_date }}</br><hr/>
    {{ blog.blog_text }}<br/><hr/>
    {% for comments in blog.comments_set.all %}
    Добавил: {{ comments.user }}<br/>
    Время добовление: {{ comments.add_date }}<br/>
    Коментария: {{ comments.comment }}<br/><hr/>
    {% endfor %}
    {% if user.is_authenticated %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-index btn-lg active" type="submit" value="comment" />
</form>
    {% else %}
        <h5>Что бы оставить коментарии пожалуйста<a href="/register/"> регистрируйтесь</a></h5>

    {% endif %}
</div>
</body>
{% endblock %}

apps/blog/templates/types.html
{% extends 'base.html' %}

{% block content %}
<body>
<div class="block-body">
    {% for blog in blogtypes.blog_set.all %}
   Тип: {{ blog.blog_type }}</br>
   Добавил: {{ blog.user }}</br>
   Название стати: {{ blog.blog_name }}</br>
   Время добовление: {{ blog.add_date }}</br>
    <a href="/type/{{ blog.id }}"> Читать... </a><hr/>
    {% endfor %}
</div>
</body>
{% endblock %}